pfish pull -c 'Yeast Display'
pfish pull -c 'Yeast Display' -l 'YeastDisplayShows'
pfish pull -c 'Yeast Display' -l 'YeastDisplayHelper'
pfish pull -c 'Yeast Display' -l 'FastMixAndQuench'
pfish pull -c 'Yeast Display' -l 'WashYeast'
pfish pull -c 'Yeast Display' -l 'NormalizeCultureDensity'
pfish pull -c 'Yeast Display' -l 'PrepareTreatmentDilutions'
pfish pull -c 'Yeast Display' -l 'LabelWithAntibody'
pfish pull -c 'Yeast Display' -l 'ChallengeAndLabelDebug'
pfish pull -c 'Yeast Display' -l 'ChallengeAndLabelHelper'